Creating project
Dziarnek/Choinka pull request #1
Opened 2017-10-31 22:08 UTC by Dziarnek

2017-11-02 22:12 UTC, matwjablonski requested changes

2017-11-02 22:12 UTC, matwjablonski commented on js/scripts.js
> +    for (var i = 0 ; i < layers ; i++ ) {
remove space before `;`

2017-11-02 22:12 UTC, matwjablonski commented on js/scripts.js
> +        for (var j = 0 ; j < i ; j++) {
remove space before `;`

2017-11-04 01:41 UTC, Dziarnek commented on js/scripts.js
> +    for (var i = 0 ; i < layers ; i++ ) {
Done :)

2017-11-04 01:41 UTC, Dziarnek commented on js/scripts.js
> +        for (var j = 0 ; j < i ; j++) {
Done :)

2017-11-26 21:23 UTC, merged